# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: Fire
email: hemangsk@gmail.com
description: "A framework for scientific computing with various reusable tools
and utilities."
url: "https://jayjaybillings.github.io"
baseurl: "/fire"
twitter_username: jayjaybillings
github_username:  jayjaybillings

# Markdown support
markdown: kramdown
highlighter: rouge

# Sass support
sass:
    sass_dir: _sass
